version: "0.1"
services:
  app:
    build: .
    container_name: java_app
    ports:
      - "8080:8080"   
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-container:5432/task_manager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - postgres_net   

networks:
  postgres_net:
    external: true   
